language: java
jdk:
  - openjdk8
script:
  - cd textwar_pom
  - mvn clean compile package install
  - cd ..
  - cd textwar
  - mvn clean compile package install
  - cd ..
  - cd textwar_protocol
  - mvn clean compile package install
  - cd ..
  - cd textwar_plugin
  - mvn clean compile package install
  - cd ..
  - cd textwar_console
  - mvn clean compile package install
  - cd ..
  - cd textwar_client_connector
  - mvn clean compile package install
after_success:
  - export CODECOV_TOKEN="token"
  - bash <(curl -s https://codecov.io/bash)