language: java
jdk:
  - openjdk8
script:
  - mvn compile package install -f textwar_pom/pom.xml
  - mvn compile package install -f textwar/pom.xml
  - mvn compile package install -f textwar_protocol/pom.xml
  - mvn compile package install -f textwar_plugin/pom.xml
  - mvn compile package install -f textwar_console/pom.xml
  - mvn compile package install -f textwar_client_connector/pom.xml